### ISSUE TITLE
Order of "Play All" is messed up, after drag and drop

### ISSUE THREAD

**Issue by sebastianjung** [rileyjshaw/po-33#1]
Hey there,

thank you for your awesome utility tool.

It seems that it messes up the order of playing the samples when pressing "play all" after changing the order via drag and drop on the phone (tested on chrome mobile) 

EDIT: Also happens on Chrome on Windows 10 (Version 87.0.4280.88 (64-Bit))

**Comment by rileyjshaw** [comment]
@sebastianjung I’m sorry for the huge delay in getting back to you.

I’m having trouble reproducing this bug. Are you able to share some of the audio samples that you encounter this issue with?

**Comment by rileyjshaw** [comment]
Ah! I just found a bug where the “Play all” order gets messed up after dragging a sample out of the grid to delete it.

I just pushed a fix, so I’m closing this issue for now. Please test if it’s fixed for you too. If you still notice the bug, please re-open this issue and give me an updated report.

Thanks for logging this, and I’m glad you’re getting some use out of the utility.
