### ISSUE TITLE
App hangs when dragging and dropping too much

### ISSUE THREAD

**Issue by sebastianjung** [rileyjshaw/po-33#2]
It seems the drag and drop functionality hangs up at some point, when used to extensivley.

Also the sound you want to pull out to be delete does not get deleted but another one instead.

Here's an image of the app hanging
![image](https://user-images.githubusercontent.com/17472892/104087953-93cf2c00-5263-11eb-87de-85296c3f18c6.png)

**Comment by rileyjshaw** [comment]
@sebastianjung I just updated the [underlying drag and drop library](https://shopify.github.io/draggable/) to the latest version. I can no-longer reproduce this error after the change.

Can you let me know if that fixed the error?

**Comment by rileyjshaw** [comment]
> Also the sound you want to pull out to be delete does not get deleted but another one instead.

Thanks for logging this, I clearly didn’t test the drag and drop behaviour thoroughly enough :) I just pushed a change that should fix this.

Please give it a test if you’re able, and feel free to re-open this issue (or log a new one) if you catch any more bugs.
